import { useState } from "react";
import TranslateBox from "../components/TranslateBox";
import ExamplePhrases from "../components/ExamplePhrases";
import InfoCards from "../components/InfoCards";

export default function TranslatorPage() {
    const [inputText, setInputText] = useState("");

    return (
        <main className="max-w-6xl mx-auto px-4 sm:px-6 py-10 sm:py-14">

            {/* Hero Section */}
            <section className="text-center mb-14">
                <div className="inline-flex items-center gap-2 bg-emerald-950/50 border border-emerald-800/40 rounded-full px-4 py-2 text-emerald-400 text-xs font-semibold tracking-wider mb-5">
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
                    RESEARCH PROTOTYPE · EXPERIMENTAL EVALUATION INTERFACE
                </div>

                <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-stone-50 leading-tight tracking-tight mb-5">
                    Sinhala–English
                    <br />
                    <span className="text-emerald-400">
                        Paddy Disease Translator
                    </span>
                </h1>

                <p className="text-stone-400 text-lg max-w-3xl mx-auto leading-relaxed mb-8">
                    An experimental machine translation system developed to
                    evaluate domain-specific translation of paddy disease
                    terminology and symptom descriptions from Sinhala to English.
                </p>

                {/* Research Notice */}
                
            </section>

            {/* Translation Module */}
            <section className="mb-12">
                <TranslateBox
                    inputText={inputText}
                    setInputText={setInputText}
                />
            </section>
            <section className="text-center mb-10">
                <div className="max-w-4xl mx-auto bg-stone-900/70 border border-stone-800 rounded-2xl p-5 text-left">
                    <div className="flex items-start gap-3">
                        <div className="mt-1">
                            <div className="w-3 h-3 rounded-full bg-amber-400"></div>
                        </div>

                        <div>
                            <h3 className="text-amber-400 font-semibold mb-2">
                                Research Evaluation Notice
                            </h3>

                            <p className="text-sm text-stone-300 leading-relaxed">
                                This interface is provided solely for research,
                                testing, and model evaluation purposes as part
                                of an academic study. Translation outputs are
                                generated by a fine-tuned Large Language Model
                                trained on paddy disease-related terminology.
                                Results may contain translation errors and
                                should not be considered professional
                                agricultural recommendations.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Example Inputs */}
            <section className="mb-12">
                <div className="mb-5">
                    <h2 className="text-xl font-semibold text-stone-100 mb-2">
                        Sample Evaluation Sentences
                    </h2>
                    <p className="text-sm text-stone-400">
                        Select a predefined Sinhala sentence to test the
                        translation model.
                    </p>
                </div>

                <ExamplePhrases onSelect={setInputText} />
            </section>

            {/* Model Information */}
            <section>
                <div className="mb-5">
                    <h2 className="text-xl font-semibold text-stone-100 mb-2">
                        Model & Research Information
                    </h2>
                    <p className="text-sm text-stone-400">
                        Overview of the dataset, training methodology, and
                        evaluation metrics used in this research.
                    </p>
                </div>

                <InfoCards />
            </section>
        </main>
    );
}